using System.Text.Json;
using System.Text.Json.Serialization;
using DbProcGen.Model;

namespace DbProcGen.Tool.Services;

public sealed class ArtifactGenerator : IArtifactGenerator
{
    public GenerationResult Generate(DbProcSpec[] specs, string outputDirectory)
    {
        ArgumentNullException.ThrowIfNull(specs);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputDirectory);

        Directory.CreateDirectory(outputDirectory);

        var generatedFiles = new List<string>();
        var manifestFamilies = new List<ProcedureFamilyManifest>();
        var existingFiles = Directory.Exists(outputDirectory)
            ? Directory.GetFiles(outputDirectory, "*.sql", SearchOption.AllDirectories).ToHashSet(StringComparer.OrdinalIgnoreCase)
            : new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var spec in specs.OrderBy(s => s.LogicalName, StringComparer.Ordinal))
        {
            var wrapperFile = GenerateWrapperProcedure(spec, outputDirectory);
            generatedFiles.Add(wrapperFile);
            existingFiles.Remove(wrapperFile);

            var workerManifests = new List<WorkerVariantManifest>();
            foreach (var route in spec.RoutingRules.Routes.OrderBy(r => r.WorkerSuffix, StringComparer.Ordinal))
            {
                var workerFile = GenerateWorkerProcedure(spec, route, outputDirectory);
                generatedFiles.Add(workerFile);
                existingFiles.Remove(workerFile);

                var conditions = route.When
                    .Select(c => new RouteConditionManifest(c.Axis, c.MatchValue))
                    .ToList();

                workerManifests.Add(new WorkerVariantManifest(
                    route.Name,
                    route.WorkerSuffix,
                    Path.GetFileName(workerFile),
                    conditions));
            }

            manifestFamilies.Add(new ProcedureFamilyManifest(
                spec.LogicalName,
                spec.Schema,
                spec.PublicProcedure,
                Path.GetFileName(wrapperFile),
                workerManifests));
        }

        var deletedFiles = new List<string>();
        foreach (var staleFile in existingFiles.OrderBy(f => f, StringComparer.Ordinal))
        {
            File.Delete(staleFile);
            deletedFiles.Add(staleFile);
        }

        // Generate manifest with deterministic timestamp (use "generation-manifest" for determinism)
        var manifest = new GenerationManifest("generation-manifest", manifestFamilies);
        var manifestFile = GenerateManifest(manifest, outputDirectory);
        generatedFiles.Add(manifestFile);

        return new GenerationResult(generatedFiles, deletedFiles, manifestFile);
    }

    private static string GenerateWrapperProcedure(DbProcSpec spec, string outputDirectory)
    {
        var fileName = $"{spec.Schema}_{spec.PublicProcedure}.sql";
        var filePath = Path.Combine(outputDirectory, fileName);

        var parameters = BuildProcedureParameters(spec);
        var routeBranches = BuildRouteBranches(spec);
        var defaultRoute = ResolveDefaultRoute(spec);
        var forwardedParameters = BuildForwardedParameters(spec);

        var content = $@"-- <auto-generated>
--   This file was generated by DbProcGen.
--   Any changes to this file will be overwritten on next generation.
-- </auto-generated>

CREATE PROCEDURE [{spec.Schema}].[{spec.PublicProcedure}]
    {parameters}
AS
BEGIN
    SET NOCOUNT ON;

    -- Wrapper procedure (public SQL API)
    -- Routes to specialized worker procedures based on parameter values

{routeBranches}

    EXEC [{spec.Schema}].[{spec.PublicProcedure}_{defaultRoute.WorkerSuffix}]
        {forwardedParameters};
END
GO
";

        File.WriteAllText(filePath, content);
        return filePath;
    }

    private static string GenerateWorkerProcedure(DbProcSpec spec, DbProcRouteSpec route, string outputDirectory)
    {
        var fileName = $"{spec.Schema}_{spec.PublicProcedure}_{route.WorkerSuffix}.sql";
        var filePath = Path.Combine(outputDirectory, fileName);

        var parameters = BuildProcedureParameters(spec);
        var workerBody = BuildWorkerBody(spec, route);

        var conditions = string.Join(" AND ", route.When.Select(c =>
            $"{c.Axis} = '{c.MatchValue}'"));

        var content = $@"-- <auto-generated>
--   This file was generated by DbProcGen.
--   Any changes to this file will be overwritten on next generation.
-- </auto-generated>

CREATE PROCEDURE [{spec.Schema}].[{spec.PublicProcedure}_{route.WorkerSuffix}]
    {parameters}
AS
BEGIN
    SET NOCOUNT ON;

    -- Worker procedure for route: {route.Name}
    -- Conditions: {conditions}
    -- Specialized implementation for this parameter combination

{workerBody}
END
GO
";

        File.WriteAllText(filePath, content);
        return filePath;
    }

    private static string GenerateManifest(GenerationManifest manifest, string outputDirectory)
    {
        var filePath = Path.Combine(outputDirectory, "generation-manifest.json");

        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            DefaultIgnoreCondition = JsonIgnoreCondition.Never
        };

        var json = JsonSerializer.Serialize(manifest, options);
        File.WriteAllText(filePath, json);
        return filePath;
    }

    private static string BuildProcedureParameters(DbProcSpec spec) =>
        string.Join(",\n    ", spec.Parameters.Select(p =>
            $"@{p.Name} {p.SqlType}{(p.Required ? "" : " = NULL")}"));

    private static string BuildForwardedParameters(DbProcSpec spec) =>
        string.Join(",\n        ", spec.Parameters.Select(p => $"@{p.Name} = @{p.Name}"));

    private static string BuildRouteBranches(DbProcSpec spec)
    {
        var routes = spec.RoutingRules.Routes.ToArray();
        if (routes.Length == 0)
        {
            return "    -- No routes defined.";
        }

        var lines = new List<string>();
        for (var i = 0; i < routes.Length; i++)
        {
            var route = routes[i];
            var predicate = BuildRoutePredicate(spec, route);
            var forwardedParameters = BuildForwardedParameters(spec);
            var branchKeyword = i == 0 ? "IF" : "ELSE IF";
            lines.Add($@"    {branchKeyword} {predicate}
    BEGIN
        EXEC [{spec.Schema}].[{spec.PublicProcedure}_{route.WorkerSuffix}]
            {forwardedParameters};
        RETURN;
    END");
        }

        return string.Join("\n\n", lines);
    }

    private static DbProcRouteSpec ResolveDefaultRoute(DbProcSpec spec)
    {
        if (!string.IsNullOrWhiteSpace(spec.RoutingRules.DefaultRoute))
        {
            var namedDefault = spec.RoutingRules.Routes.FirstOrDefault(r =>
                string.Equals(r.Name, spec.RoutingRules.DefaultRoute, StringComparison.Ordinal));

            if (namedDefault is not null)
            {
                return namedDefault;
            }
        }

        return spec.RoutingRules.Routes
            .OrderBy(r => r.WorkerSuffix, StringComparer.Ordinal)
            .First();
    }

    private static string BuildRoutePredicate(DbProcSpec spec, DbProcRouteSpec route)
    {
        if (route.When.Count == 0)
        {
            return "1 = 1";
        }

        var predicates = new List<string>();
        foreach (var condition in route.When.OrderBy(c => c.Axis, StringComparer.Ordinal))
        {
            var axis = spec.SpecializationAxes.FirstOrDefault(a =>
                string.Equals(a.Name, condition.Axis, StringComparison.Ordinal));

            if (axis is null)
            {
                predicates.Add("1 = 0");
                continue;
            }

            var parameter = spec.Parameters.FirstOrDefault(p =>
                string.Equals(p.Name, axis.Parameter, StringComparison.Ordinal));

            if (parameter is null)
            {
                predicates.Add("1 = 0");
                continue;
            }

            var literal = FormatSqlLiteral(condition.MatchValue, parameter.SqlType);
            predicates.Add($"@{axis.Parameter} = {literal}");
        }

        return string.Join(" AND ", predicates);
    }

    private static string FormatSqlLiteral(string value, string sqlType)
    {
        var normalizedType = sqlType.Trim().ToLowerInvariant();
        var normalizedValue = value.Trim();

        if (normalizedType.StartsWith("bit", StringComparison.Ordinal))
        {
            if (string.Equals(normalizedValue, "true", StringComparison.OrdinalIgnoreCase) ||
                normalizedValue == "1")
            {
                return "1";
            }

            if (string.Equals(normalizedValue, "false", StringComparison.OrdinalIgnoreCase) ||
                normalizedValue == "0")
            {
                return "0";
            }
        }

        var escaped = normalizedValue.Replace("'", "''", StringComparison.Ordinal);
        return $"'{escaped}'";
    }

    private static string BuildWorkerBody(DbProcSpec spec, DbProcRouteSpec route)
    {
        if (string.Equals(spec.Schema, "dbo", StringComparison.Ordinal) &&
            string.Equals(spec.PublicProcedure, "GetUsersByFilter", StringComparison.Ordinal))
        {
            if (string.Equals(route.WorkerSuffix, "name_paged", StringComparison.Ordinal))
            {
                return @"    DECLARE @EffectivePageSize int = CASE
        WHEN @PageSize IS NULL OR @PageSize < 1 THEN 25
        ELSE @PageSize
    END;

    DECLARE @EffectivePageNumber int = CASE
        WHEN @PageNumber IS NULL OR @PageNumber < 1 THEN 1
        ELSE @PageNumber
    END;

    DECLARE @Offset int = (@EffectivePageNumber - 1) * @EffectivePageSize;

    SET @PageSize = @EffectivePageSize;

    SELECT
        CAST(u.[UserId] AS int) AS [UserId],
        CAST(u.[UserName] AS nvarchar(200)) AS [DisplayName]
    FROM [dbo].[Users] AS u
    WHERE @FilterType = 'Name'
      AND @FilterValue IS NOT NULL
      AND u.[UserName] LIKE @FilterValue + '%'
    ORDER BY u.[UserName], u.[UserId]
    OFFSET @Offset ROWS
    FETCH NEXT @PageSize ROWS ONLY;";
            }

            if (string.Equals(route.WorkerSuffix, "email_unpaged", StringComparison.Ordinal))
            {
                return @"    SELECT
        CAST(u.[UserId] AS int) AS [UserId],
        CAST(u.[Email] AS nvarchar(200)) AS [DisplayName]
    FROM [dbo].[Users] AS u
    WHERE @FilterType = 'Email'
      AND @FilterValue IS NOT NULL
      AND u.[Email] = @FilterValue
    ORDER BY u.[Email], u.[UserId];";
            }
        }

        var resultColumns = string.Join(",\n        ", spec.ResultContract.Columns.Select(c =>
            $"CAST(NULL AS {c.SqlType}) AS [{c.Name}]"));

        return $@"    SELECT
        {resultColumns}
    WHERE 1 = 0;";
    }
}
