using DbProcGen.Model;

namespace DbProcGen.Tool.Services;

public sealed class ArtifactGenerator : IArtifactGenerator
{
    public GenerationResult Generate(DbProcSpec[] specs, string outputDirectory)
    {
        ArgumentNullException.ThrowIfNull(specs);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputDirectory);

        Directory.CreateDirectory(outputDirectory);

        var generatedFiles = new List<string>();
        var existingFiles = Directory.Exists(outputDirectory)
            ? Directory.GetFiles(outputDirectory, "*.sql", SearchOption.AllDirectories).ToHashSet(StringComparer.OrdinalIgnoreCase)
            : new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var spec in specs.OrderBy(s => s.LogicalName, StringComparer.Ordinal))
        {
            var wrapperFile = GenerateWrapperProcedure(spec, outputDirectory);
            generatedFiles.Add(wrapperFile);
            existingFiles.Remove(wrapperFile);

            foreach (var route in spec.RoutingRules.Routes.OrderBy(r => r.WorkerSuffix, StringComparer.Ordinal))
            {
                var workerFile = GenerateWorkerProcedure(spec, route, outputDirectory);
                generatedFiles.Add(workerFile);
                existingFiles.Remove(workerFile);
            }
        }

        var deletedFiles = new List<string>();
        foreach (var staleFile in existingFiles.OrderBy(f => f, StringComparer.Ordinal))
        {
            File.Delete(staleFile);
            deletedFiles.Add(staleFile);
        }

        return new GenerationResult(generatedFiles, deletedFiles);
    }

    private static string GenerateWrapperProcedure(DbProcSpec spec, string outputDirectory)
    {
        var fileName = $"{spec.Schema}_{spec.PublicProcedure}.sql";
        var filePath = Path.Combine(outputDirectory, fileName);

        var parameters = string.Join(",\n    ", spec.Parameters.Select(p =>
            $"@{p.Name} {p.SqlType}{(p.Required ? "" : " = NULL")}"));

        var resultColumns = string.Join(",\n        ", spec.ResultContract.Columns.Select(c =>
            $"{c.Name} {c.SqlType}{(c.Nullable ? " NULL" : " NOT NULL")}"));

        var content = $@"-- <auto-generated>
--   This file was generated by DbProcGen.
--   Any changes to this file will be overwritten on next generation.
-- </auto-generated>

CREATE OR ALTER PROCEDURE [{spec.Schema}].[{spec.PublicProcedure}]
    {parameters}
AS
BEGIN
    SET NOCOUNT ON;

    -- Wrapper procedure (public SQL API)
    -- Routes to specialized worker procedures based on parameter values
    
    -- TODO: Implement routing logic
    -- Placeholder: return empty result set matching contract
    
    SELECT
        {resultColumns}
    WHERE 1 = 0;
END
GO
";

        File.WriteAllText(filePath, content);
        return filePath;
    }

    private static string GenerateWorkerProcedure(DbProcSpec spec, DbProcRouteSpec route, string outputDirectory)
    {
        var fileName = $"{spec.Schema}_{spec.PublicProcedure}_{route.WorkerSuffix}.sql";
        var filePath = Path.Combine(outputDirectory, fileName);

        var parameters = string.Join(",\n    ", spec.Parameters.Select(p =>
            $"@{p.Name} {p.SqlType}{(p.Required ? "" : " = NULL")}"));

        var resultColumns = string.Join(",\n        ", spec.ResultContract.Columns.Select(c =>
            $"{c.Name} {c.SqlType}{(c.Nullable ? " NULL" : " NOT NULL")}"));

        var conditions = string.Join(" AND ", route.When.Select(c =>
            $"{c.Axis} = '{c.MatchValue}'"));

        var content = $@"-- <auto-generated>
--   This file was generated by DbProcGen.
--   Any changes to this file will be overwritten on next generation.
-- </auto-generated>

CREATE OR ALTER PROCEDURE [{spec.Schema}].[{spec.PublicProcedure}_{route.WorkerSuffix}]
    {parameters}
AS
BEGIN
    SET NOCOUNT ON;

    -- Worker procedure for route: {route.Name}
    -- Conditions: {conditions}
    -- Specialized implementation for this parameter combination
    
    -- TODO: Implement specialized query logic
    -- Placeholder: return empty result set matching contract
    
    SELECT
        {resultColumns}
    WHERE 1 = 0;
END
GO
";

        File.WriteAllText(filePath, content);
        return filePath;
    }
}
