using DbProcGen.Model;
using DbProcGen.Generator;
using TUnit.Core;

namespace DbProcGen.Tool.Tests;

public sealed class ArtifactGeneratorTests
{
    [Test]
    public async Task Generate_CreatesWrapperAndWorkerFiles()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            Directory.CreateDirectory(tempDir);

            var spec = new DbProcSpec(
                "1.0",
                "TestProc",
                "dbo",
                "TestProc",
                [],
                new DbProcResultContractSpec([
                    new DbProcResultColumnSpec("Id", "int", false)
                ]),
                [],
                new DbProcRoutingRulesSpec([
                    new DbProcRouteSpec("Default", [
                        new DbProcRouteConditionSpec("TestAxis", "TestValue")
                    ], "default", "SELECT CAST(1 AS int) AS [Id];")
                ], null),
                []);

            var generator = new ArtifactGenerator();
            var result = generator.Generate([spec], tempDir);

            await Assert.That(result.GeneratedFiles.Count).IsEqualTo(3); // wrapper + worker + manifest
            await Assert.That(result.GeneratedFiles).Any(f => f.EndsWith("dbo_TestProc.sql"));
            await Assert.That(result.GeneratedFiles).Any(f => f.EndsWith("dbo_TestProc_default.sql"));
            await Assert.That(result.ManifestFile).IsNotNull();
            await Assert.That(result.ManifestFile!.EndsWith("generation-manifest.json")).IsTrue();

            var wrapperContent = File.ReadAllText(result.GeneratedFiles.First(f => f.EndsWith("dbo_TestProc.sql")));
            await Assert.That(wrapperContent).Contains("<auto-generated>");
            await Assert.That(wrapperContent).Contains("CREATE PROCEDURE [dbo].[TestProc]");
            await Assert.That(wrapperContent).Contains("THROW 50001, 'No matching route for generated wrapper procedure.', 1;");
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Test]
    public async Task Generate_RemovesStaleFiles()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            Directory.CreateDirectory(tempDir);

            var staleFile = Path.Combine(tempDir, "stale.sql");
            File.WriteAllText(staleFile, "-- old content");

            var spec = new DbProcSpec(
                "1.0",
                "TestProc",
                "dbo",
                "TestProc",
                [],
                new DbProcResultContractSpec([
                    new DbProcResultColumnSpec("Id", "int", false)
                ]),
                [],
                new DbProcRoutingRulesSpec([
                    new DbProcRouteSpec("Default", [new DbProcRouteConditionSpec("Axis", "v")], "default")
                ], null),
                []);

            var generator = new ArtifactGenerator();
            var result = generator.Generate([spec], tempDir);

            await Assert.That(result.DeletedFiles).Contains(staleFile);
            await Assert.That(File.Exists(staleFile)).IsFalse();
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Test]
    public async Task Generate_DeterministicOrdering()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            Directory.CreateDirectory(tempDir);

            var specs = new[]
            {
                CreateSpec("Zebra", "z_worker"),
                CreateSpec("Alpha", "a_worker"),
                CreateSpec("Bravo", "b_worker")
            };

            var generator = new ArtifactGenerator();
            var result = generator.Generate(specs, tempDir);

            var fileNames = result.GeneratedFiles.Select(Path.GetFileName).ToArray();
            await Assert.That(fileNames[0]!.StartsWith("dbo_Alpha")).IsTrue();
            await Assert.That(fileNames[2]!.StartsWith("dbo_Bravo")).IsTrue();
            await Assert.That(fileNames[4]!.StartsWith("dbo_Zebra")).IsTrue();
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Test]
    public async Task Generate_CreatesValidManifest()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            Directory.CreateDirectory(tempDir);

            var spec = new DbProcSpec(
                "1.0",
                "GetUsersByFilter",
                "dbo",
                "GetUsersByFilter",
                [
                    new DbProcParameterSpec("FilterType", "nvarchar(32)", true),
                    new DbProcParameterSpec("IsPaged", "bit", true)
                ],
                new DbProcResultContractSpec([
                    new DbProcResultColumnSpec("UserId", "int", false),
                    new DbProcResultColumnSpec("DisplayName", "nvarchar(200)", false)
                ]),
                [],
                new DbProcRoutingRulesSpec([
                    new DbProcRouteSpec("NamePaged", [
                        new DbProcRouteConditionSpec("FilterTypeAxis", "Name"),
                        new DbProcRouteConditionSpec("PagingAxis", "true")
                    ], "name_paged"),
                    new DbProcRouteSpec("EmailUnpaged", [
                        new DbProcRouteConditionSpec("FilterTypeAxis", "Email"),
                        new DbProcRouteConditionSpec("PagingAxis", "false")
                    ], "email_unpaged")
                ], null),
                []);

            var generator = new ArtifactGenerator();
            var result = generator.Generate([spec], tempDir);

            await Assert.That(result.ManifestFile).IsNotNull();
            await Assert.That(File.Exists(result.ManifestFile!)).IsTrue();

            var manifestContent = File.ReadAllText(result.ManifestFile!);
            var manifest = System.Text.Json.JsonSerializer.Deserialize<GenerationManifest>(manifestContent,
                new System.Text.Json.JsonSerializerOptions
                {
                    PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase
                });

            await Assert.That(manifest).IsNotNull();
            await Assert.That(manifest!.Families.Count).IsEqualTo(1);

            var family = manifest.Families[0];
            await Assert.That(family.LogicalName).IsEqualTo("GetUsersByFilter");
            await Assert.That(family.Schema).IsEqualTo("dbo");
            await Assert.That(family.PublicProcedure).IsEqualTo("GetUsersByFilter");
            await Assert.That(family.WrapperFile).IsEqualTo("dbo_GetUsersByFilter.sql");
            await Assert.That(family.Workers.Count).IsEqualTo(2);

            // Verify first worker
            var worker1 = family.Workers[0];
            await Assert.That(worker1.RouteName).IsEqualTo("EmailUnpaged");
            await Assert.That(worker1.WorkerSuffix).IsEqualTo("email_unpaged");
            await Assert.That(worker1.WorkerFile).IsEqualTo("dbo_GetUsersByFilter_email_unpaged.sql");
            await Assert.That(worker1.Conditions.Count).IsEqualTo(2);
            await Assert.That(worker1.Conditions[0].Axis).IsEqualTo("FilterTypeAxis");
            await Assert.That(worker1.Conditions[0].Value).IsEqualTo("Email");

            // Verify second worker
            var worker2 = family.Workers[1];
            await Assert.That(worker2.RouteName).IsEqualTo("NamePaged");
            await Assert.That(worker2.WorkerSuffix).IsEqualTo("name_paged");
            await Assert.That(worker2.WorkerFile).IsEqualTo("dbo_GetUsersByFilter_name_paged.sql");
            await Assert.That(worker2.Conditions.Count).IsEqualTo(2);
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Test]
    public async Task Manifest_IsDeterministic()
    {
        var tempDir1 = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        var tempDir2 = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            Directory.CreateDirectory(tempDir1);
            Directory.CreateDirectory(tempDir2);

            var spec = new DbProcSpec(
                "1.0",
                "TestProc",
                "dbo",
                "TestProc",
                [],
                new DbProcResultContractSpec([
                    new DbProcResultColumnSpec("Id", "int", false)
                ]),
                [],
                new DbProcRoutingRulesSpec([
                    new DbProcRouteSpec("Route1", [new DbProcRouteConditionSpec("Axis", "v1")], "worker1"),
                    new DbProcRouteSpec("Route2", [new DbProcRouteConditionSpec("Axis", "v2")], "worker2")
                ], null),
                []);

            var generator = new ArtifactGenerator();
            var result1 = generator.Generate([spec], tempDir1);
            var result2 = generator.Generate([spec], tempDir2);

            var manifest1 = File.ReadAllText(result1.ManifestFile!);
            var manifest2 = File.ReadAllText(result2.ManifestFile!);

            await Assert.That(manifest1).IsEqualTo(manifest2);
        }
        finally
        {
            if (Directory.Exists(tempDir1)) Directory.Delete(tempDir1, true);
            if (Directory.Exists(tempDir2)) Directory.Delete(tempDir2, true);
        }
    }

    private static DbProcSpec CreateSpec(string logicalName, string workerSuffix)
    {
        return new DbProcSpec(
            "1.0",
            logicalName,
            "dbo",
            logicalName,
            [],
            new DbProcResultContractSpec([
                new DbProcResultColumnSpec("Id", "int", false)
            ]),
            [],
            new DbProcRoutingRulesSpec([
                new DbProcRouteSpec("Default", [new DbProcRouteConditionSpec("Axis", "v")], workerSuffix)
            ], null),
            []);
    }
}
