using DbProcGen.Model;
using DbProcGen.Tool.Services;
using TUnit.Core;

namespace DbProcGen.Tool.Tests;

public sealed class ArtifactGeneratorTests
{
    [Test]
    public async Task Generate_CreatesWrapperAndWorkerFiles()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            Directory.CreateDirectory(tempDir);

            var spec = new DbProcSpec(
                "1.0",
                "TestProc",
                "dbo",
                "TestProc",
                [],
                new DbProcResultContractSpec([
                    new DbProcResultColumnSpec("Id", "int", false)
                ]),
                [],
                new DbProcRoutingRulesSpec([
                    new DbProcRouteSpec("Default", [
                        new DbProcRouteConditionSpec("TestAxis", "TestValue")
                    ], "default")
                ], null),
                []);

            var generator = new ArtifactGenerator();
            var result = generator.Generate([spec], tempDir);

            await Assert.That(result.GeneratedFiles.Count).IsEqualTo(2);
            await Assert.That(result.GeneratedFiles).Any(f => f.EndsWith("dbo_TestProc.sql"));
            await Assert.That(result.GeneratedFiles).Any(f => f.EndsWith("dbo_TestProc_default.sql"));

            var wrapperContent = File.ReadAllText(result.GeneratedFiles.First(f => f.EndsWith("dbo_TestProc.sql")));
            await Assert.That(wrapperContent).Contains("<auto-generated>");
            await Assert.That(wrapperContent).Contains("CREATE OR ALTER PROCEDURE [dbo].[TestProc]");
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Test]
    public async Task Generate_RemovesStaleFiles()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            Directory.CreateDirectory(tempDir);

            var staleFile = Path.Combine(tempDir, "stale.sql");
            File.WriteAllText(staleFile, "-- old content");

            var spec = new DbProcSpec(
                "1.0",
                "TestProc",
                "dbo",
                "TestProc",
                [],
                new DbProcResultContractSpec([
                    new DbProcResultColumnSpec("Id", "int", false)
                ]),
                [],
                new DbProcRoutingRulesSpec([
                    new DbProcRouteSpec("Default", [], "default")
                ], null),
                []);

            var generator = new ArtifactGenerator();
            var result = generator.Generate([spec], tempDir);

            await Assert.That(result.DeletedFiles).Contains(staleFile);
            await Assert.That(File.Exists(staleFile)).IsFalse();
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Test]
    public async Task Generate_DeterministicOrdering()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        try
        {
            Directory.CreateDirectory(tempDir);

            var specs = new[]
            {
                CreateSpec("Zebra", "z_worker"),
                CreateSpec("Alpha", "a_worker"),
                CreateSpec("Bravo", "b_worker")
            };

            var generator = new ArtifactGenerator();
            var result = generator.Generate(specs, tempDir);

            var fileNames = result.GeneratedFiles.Select(Path.GetFileName).ToArray();
            await Assert.That(fileNames[0]!.StartsWith("dbo_Alpha")).IsTrue();
            await Assert.That(fileNames[2]!.StartsWith("dbo_Bravo")).IsTrue();
            await Assert.That(fileNames[4]!.StartsWith("dbo_Zebra")).IsTrue();
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    private static DbProcSpec CreateSpec(string logicalName, string workerSuffix)
    {
        return new DbProcSpec(
            "1.0",
            logicalName,
            "dbo",
            logicalName,
            [],
            new DbProcResultContractSpec([
                new DbProcResultColumnSpec("Id", "int", false)
            ]),
            [],
            new DbProcRoutingRulesSpec([
                new DbProcRouteSpec("Default", [], workerSuffix)
            ], null),
            []);
    }
}
